name: Debug

on:
  workflow_dispatch:
    inputs:
      tmate:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'windows-latest'
        run: |
          choco install html-tidy
      - name: Configure git
        run: |
          git config --global user.email "ki@example.com"
          git config --global user.name "Ki GithubActions"
      - name: Checkout a different branch
        run: |
          git checkout github-actions
      - name: Install dependencies
        run: |
          pip install pytest wheel
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Install ki
        run: |
          pip install .
      - name: Setup vim
        uses: rhysd/action-setup-vim@v1
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate }}
        uses: mxschmitt/action-tmate@v3
